version: "3.9"

services:
  payara-1:
    image: payara/server-full:6.2024.3-jdk17
    container_name: payara-1
    restart: unless-stopped
    environment:
      - SERVICE_ID=payara-1
      - SERVICE_ADDRESS=payara-1
      - SERVICE_PORT=8080
    depends_on:
      - consul
    ports:
      - "8080:8080"
      - "4848:4848"

  payara-2:
    image: payara/server-full:6.2024.3-jdk17
    container_name: payara-2
    restart: unless-stopped
    environment:
      - SERVICE_ID=payara-2
      - SERVICE_ADDRESS=payara-2
      - SERVICE_PORT=8080
    depends_on:
      - consul
    ports:
      - "8081:8080"
      - "4849:4848"

  payara-3:
    image: payara/server-full:6.2024.3-jdk17
    container_name: payara-3
    restart: unless-stopped
    environment:
      - SERVICE_ID=payara-3
      - SERVICE_ADDRESS=payara-3
      - SERVICE_PORT=8080
    depends_on:
      - consul
    ports:
      - "8082:8080"
      - "4850:4848"

  postgres:
    image: postgres:16-alpine
    container_name: called-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: called_db
      POSTGRES_USER: called_user
      POSTGRES_PASSWORD: called_pass

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

  consul:
    image: consul:1.15.4
    container_name: called-consul
    restart: unless-stopped
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"

volumes:
  payara-domain:
  pgdata:
