version: "3.9"

services:
  consul:
    image: consul:1.15.4
    container_name: called-consul
    restart: unless-stopped
    command: agent -dev -client=0.0.0.0 -dns-port=53
    ports:
      - "8500:8500"        # UI / HTTP API
      - "8600:8600/udp"    # (можно оставить, если хочешь снаружи DNS дергать отдельно)
    networks:
      app-net:
        ipv4_address: 172.30.0.10

  payara-1:
    image: payara/server-full:6.2024.3-jdk17
    container_name: payara-1
    restart: unless-stopped
    environment:
      - SERVICE_ID=payara-1
      - SERVICE_ADDRESS=payara-1
      - SERVICE_PORT=8080
    depends_on:
      - consul
    ports:
      - "8080:8080"
      - "4848:4848"
    networks:
      app-net:

  postgres:
    image: postgres:16-alpine
    container_name: called-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: called_db
      POSTGRES_USER: called_user
      POSTGRES_PASSWORD: called_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      app-net:

  config-server:
    build: ./spring-cloud/config-server
    container_name: config-server
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./spring-cloud/spring-config-repo:/config-repo
    networks:
      app-net:

  eureka-server:
    build: ./spring-cloud/eureka-server
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      app-net:

  api-gateway:
    build: ./spring-cloud/api-gateway
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8088:8080"
    depends_on:
      - config-server
      - eureka-server
      - consul
    networks:
      app-net:
        ipv4_address: 172.30.0.11
    dns:
      - 172.30.0.10

  called-adapter-1:
    build: ./spring-cloud/called-adapter
    container_name: called-adapter-1
    restart: unless-stopped
    depends_on:
      - config-server
      - eureka-server
    networks:
      app-net:

  called-adapter-2:
    build: ./spring-cloud/called-adapter
    container_name: called-adapter-2
    restart: unless-stopped
    depends_on:
      - config-server
      - eureka-server
    networks:
      app-net:

  caller-service:
    build: ./spring-cloud/caller-service
    container_name: caller-service
    restart: unless-stopped
    depends_on:
      - config-server
      - eureka-server
      - called-adapter-1
    networks:
      app-net:

volumes:
  payara-domain:
  pgdata:

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
